ds:
  superBoot:
    master:
      url= jdbc:mysql://127.0.0.1:3202/superboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username=superboot
      password=123456
      driverClassName=com.mysql.jdbc.Driver
      type=com.alibaba.druid.pool.DruidDataSource
    slave:
      url= jdbc:mysql://127.0.0.1:3202/superboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username= superboot
      password= 123456
      driverClassName=com.mysql.jdbc.Driver
      type=com.alibaba.druid.pool.DruidDataSource
server:
  port: 3306
